import type { AffixDefinition, ElementType, HeroClass, HeroDefinition, ReactionDefinition, RelicDefinition, SkillDefinition, UpgradeOption } from "@/game/types";

export const ARENA_WIDTH = 960;
export const ARENA_HEIGHT = 540;
export const DEMO_DURATION = 240;

export const heroes: Record<HeroClass, HeroDefinition> = {
  warrior: {
    id: "warrior",
    name: "灰烬卫士",
    title: "近战爆发",
    flavor: "挥舞巨刃冲进怪群，用贴身斩击和火焰震荡撕开缺口。",
    weapon: "裂火巨刃",
    color: "#ff9d5c",
    baseHp: 180,
    moveSpeed: 188,
    attackInterval: 0.7,
    starterSkillId: "ember-cleave",
    tags: ["高生命", "近身清场", "火焰联动"],
    trait: "近战命中时恢复少量生命，越靠近敌群越强。",
  },
  ranger: {
    id: "ranger",
    name: "星羽游侠",
    title: "远程弹幕",
    flavor: "利用高机动和穿透箭风筝敌群，适合叠投射物和感电效果。",
    weapon: "折光长弓",
    color: "#72f3c7",
    baseHp: 132,
    moveSpeed: 214,
    attackInterval: 0.42,
    starterSkillId: "ricochet-shot",
    tags: ["高攻速", "远程穿透", "连锁雷击"],
    trait: "保持移动时提升暴击率，适合边走位边打输出。",
  },
  mage: {
    id: "mage",
    name: "暮光术师",
    title: "法术构筑",
    flavor: "以法球和元素爆发清理战场，技能组合最丰富。",
    weapon: "棱镜法典",
    color: "#85a9ff",
    baseHp: 116,
    moveSpeed: 182,
    attackInterval: 0.9,
    starterSkillId: "arcane-orb",
    tags: ["高技能伤害", "元素附魔", "大范围 AOE"],
    trait: "每次主动施法会强化下一次自动攻击。",
  },
};

export const skills: Record<string, SkillDefinition> = {
  "ember-cleave": {
    id: "ember-cleave",
    name: "灰烬横斩",
    category: "auto",
    baseElement: "physical",
    baseDamage: 26,
    cooldown: 0.7,
    radius: 72,
    projectileSpeed: 0,
    duration: 0.1,
    description: "朝最近敌人方向挥出短距离横斩，适合叠范围和火焰附魔。",
  },
  "ricochet-shot": {
    id: "ricochet-shot",
    name: "折光箭",
    category: "auto",
    baseElement: "physical",
    baseDamage: 18,
    cooldown: 0.42,
    radius: 10,
    projectileSpeed: 360,
    duration: 1.6,
    description: "自动射出穿透箭矢，适合叠攻速、暴击与雷电链射。",
  },
  "arcane-orb": {
    id: "arcane-orb",
    name: "秘能法球",
    category: "auto",
    baseElement: "arcane",
    baseDamage: 28,
    cooldown: 0.9,
    radius: 16,
    projectileSpeed: 260,
    duration: 2.1,
    description: "发射缓慢法球，命中后爆开，适合法师的元素扩散玩法。",
  },
  "flame-nova": {
    id: "flame-nova",
    name: "烈焰新星",
    category: "active",
    baseElement: "fire",
    baseDamage: 42,
    cooldown: 5.6,
    radius: 110,
    projectileSpeed: 0,
    duration: 0.2,
    description: "按空格释放，围绕自身爆发火焰，快速清理近身敌群。",
  },
  "frost-lance": {
    id: "frost-lance",
    name: "霜棱穿刺",
    category: "active",
    baseElement: "ice",
    baseDamage: 34,
    cooldown: 4.8,
    radius: 12,
    projectileSpeed: 420,
    duration: 2.2,
    description: "向最近敌人方向射出三枚冰棱，命中时施加减速。",
  },
  "thunder-call": {
    id: "thunder-call",
    name: "雷链召引",
    category: "active",
    baseElement: "lightning",
    baseDamage: 38,
    cooldown: 6.2,
    radius: 170,
    projectileSpeed: 0,
    duration: 0.2,
    description: "按空格召落雷链，优先打击密集敌群并传播感电。",
  },
  "whirling-guard": {
    id: "whirling-guard",
    name: "贴身旋刃",
    category: "active",
    baseElement: "physical",
    baseDamage: 28,
    cooldown: 4.9,
    radius: 88,
    projectileSpeed: 0,
    duration: 0.3,
    description: "围绕自身卷起旋刃，快速切开贴身敌群。",
    tags: ["burst", "close-range"],
    shared: true,
  },
  "seeker-blades": {
    id: "seeker-blades",
    name: "追踪飞刃",
    category: "active",
    baseElement: "arcane",
    baseDamage: 24,
    cooldown: 5.4,
    radius: 10,
    projectileSpeed: 280,
    duration: 2.1,
    description: "释放追踪飞刃，优先追击高价值目标并补足收尾能力。",
    tags: ["projectile", "tracking"],
    shared: true,
  },
  "shock-pulse": {
    id: "shock-pulse",
    name: "重压震荡",
    category: "active",
    baseElement: "physical",
    baseDamage: 36,
    cooldown: 5.8,
    radius: 132,
    projectileSpeed: 0,
    duration: 0.24,
    description: "朝前方打出重压冲击，适合爆发控场和清开通路。",
    tags: ["burst", "close-range"],
    shared: true,
  },
  "orbit-sigil": {
    id: "orbit-sigil",
    name: "环绕法器",
    category: "active",
    baseElement: "arcane",
    baseDamage: 22,
    cooldown: 6.2,
    radius: 14,
    projectileSpeed: 0,
    duration: 4.2,
    description: "召出环绕法器，为自身周围持续补伤并拦截敌群。",
    tags: ["orbit", "projectile"],
    shared: true,
  },
  "lure-mine": {
    id: "lure-mine",
    name: "诱导地雷",
    category: "active",
    baseElement: "fire",
    baseDamage: 40,
    cooldown: 6.6,
    radius: 96,
    projectileSpeed: 0,
    duration: 1.1,
    description: "在身前布下延迟爆炸地雷，适合拉怪后引爆清场。",
    tags: ["trap", "burst"],
    shared: true,
  },
};

export const elementPalette: Record<ElementType, string> = {
  physical: "#f7d9a0",
  fire: "#ff7a45",
  ice: "#80d6ff",
  lightning: "#e4d06a",
  arcane: "#b48cff",
};

export const statUpgradePool = [
  {
    id: "stat-vitality",
    kind: "stat-mod" as const,
    title: "钢铁体魄",
    description: "最大生命 +24，并立刻回复 18 点生命。",
    rarity: "common" as const,
    value: 24,
  },
  {
    id: "stat-surge",
    kind: "stat-mod" as const,
    title: "疾行步法",
    description: "移动速度 +10%，走位更容易拉扯怪群。",
    rarity: "common" as const,
    value: 0.1,
  },
  {
    id: "stat-focus",
    kind: "stat-mod" as const,
    title: "战斗专注",
    description: "伤害 +12%，所有技能都吃到强化。",
    rarity: "rare" as const,
    value: 0.12,
  },
  {
    id: "stat-bloom",
    kind: "stat-mod" as const,
    title: "扩散回路",
    description: "范围 +12%，更容易打出 AOE 和元素扩散。",
    rarity: "rare" as const,
    value: 0.12,
  },
  {
    id: "stat-precision",
    kind: "stat-mod" as const,
    title: "致命校准",
    description: "暴击率 +8%，搭配游侠与法师收益更高。",
    rarity: "epic" as const,
    value: 0.08,
  },
];

export const elementChoices: { element: ElementType; label: string; description: string }[] = [
  {
    element: "fire",
    label: "余烬附魔",
    description: "主武器附带火焰，命中后施加燃烧持续伤害。",
  },
  {
    element: "ice",
    label: "寒潮附魔",
    description: "主武器附带寒冰，命中后大幅减速敌人。",
  },
  {
    element: "lightning",
    label: "雷霆附魔",
    description: "主武器附带雷电，命中后向附近敌人弹出电弧。",
  },
];

export const unlockableSkillIds = [
  "flame-nova",
  "frost-lance",
  "thunder-call",
  "whirling-guard",
  "seeker-blades",
  "shock-pulse",
  "orbit-sigil",
  "lure-mine",
];

export const affixPool: AffixDefinition[] = [
  {
    id: "affix-bounce-shot",
    name: "弹射弹道",
    description: "英雄投射物命中后会优先折向附近目标，连段更稳定。",
    rarity: "rare",
    category: "projectile",
  },
  {
    id: "affix-deep-pierce",
    name: "贯穿整列",
    description: "英雄投射物额外穿透 2 个目标，更适合清长线怪群。",
    rarity: "rare",
    category: "projectile",
  },
  {
    id: "affix-return-loop",
    name: "回旋轨迹",
    description: "英雄投射物飞行过半后折返，形成二次扫线。",
    rarity: "epic",
    category: "projectile",
  },
  {
    id: "affix-blast-wave",
    name: "冲击扩散",
    description: "主动技能和爆炸类效果范围扩大，更容易覆盖怪群。",
    rarity: "common",
    category: "area",
  },
  {
    id: "affix-orbit-harmonics",
    name: "环绕增幅",
    description: "环绕法器半径提高，并增强近身构筑的防线厚度。",
    rarity: "common",
    category: "area",
  },
  {
    id: "affix-cooldown-weave",
    name: "冷却压缩",
    description: "主动技能冷却缩短，能更频繁打出节奏点。",
    rarity: "rare",
    category: "tempo",
  },
  {
    id: "affix-kill-refresh",
    name: "击杀返还",
    description: "击杀敌人时返还部分主动技能冷却，利于连续压场。",
    rarity: "epic",
    category: "tempo",
  },
  {
    id: "affix-ember-trail",
    name: "余烬延烧",
    description: "燃烧持续更久，让火焰路线在中局更容易成型。",
    rarity: "common",
    category: "element",
  },
  {
    id: "affix-static-spread",
    name: "感电蔓延",
    description: "雷电连锁和感电扩散范围提高，更容易形成连锁清场。",
    rarity: "rare",
    category: "element",
  },
];

export const relicPool: RelicDefinition[] = [
  {
    id: "relic-overload-codex",
    name: "过载法典",
    description: "主动技能伤害显著提高，但基础冷却更长；击杀时返还部分主动技能冷却。",
    summary: "主动技能爆发更高，击杀可返还冷却。",
    rarity: "epic",
    category: "active",
    focusSkillIds: ["flame-nova", "frost-lance", "thunder-call", "whirling-guard", "seeker-blades", "shock-pulse", "orbit-sigil", "lure-mine"],
  },
  {
    id: "relic-split-plume",
    name: "裂轨羽冠",
    description: "英雄投射物命中后裂出副弹道，形成更稳定的多段清场，但单发伤害略降。",
    summary: "投射物命中后裂出副弹道。",
    rarity: "epic",
    category: "projectile",
    focusSkillIds: ["ricochet-shot", "arcane-orb", "frost-lance", "seeker-blades", "orbit-sigil"],
  },
  {
    id: "relic-forge-emblem",
    name: "熔炉徽记",
    description: "贴近敌群时获得减伤与增伤，主动鼓励贴身压场和近身站场打法。",
    summary: "贴近敌群时减伤并增伤。",
    rarity: "rare",
    category: "stance",
    focusSkillIds: ["ember-cleave", "whirling-guard", "shock-pulse", "orbit-sigil"],
  },
  {
    id: "relic-star-chart",
    name: "静止星盘",
    description: "停留蓄势时，环绕物、地雷和震荡类效果会进一步放大，适合布置战场。",
    summary: "停留蓄势时，控场技能更强。",
    rarity: "rare",
    category: "stance",
    focusSkillIds: ["shock-pulse", "orbit-sigil", "lure-mine"],
  },
  {
    id: "relic-element-vessel",
    name: "偏元素容器",
    description: "锁定当前主元素并显著放大对应行为，例如燃烧更久、冰缓更强、雷链更远。",
    summary: "锁定并放大当前主元素方向。",
    rarity: "rare",
    category: "elemental",
    focusElements: ["fire", "ice", "lightning"],
  },
  {
    id: "relic-hunt-signet",
    name: "狩猎契印",
    description: "职业核心机制达成条件时，会额外引出通用收益，进一步放大职业节奏。",
    summary: "职业核心触发时追加通用收益。",
    rarity: "epic",
    category: "hero-bridge",
  },
];

export const reactionTable: ReactionDefinition[] = [
  {
    id: "overload-burst",
    name: "超载爆裂",
    description: "燃烧目标受到雷击时触发爆裂，形成一次小范围开路伤害。",
    baseElement: "fire",
    triggerElement: "lightning",
    damageMultiplier: 0.95,
    radius: 82,
  },
  {
    id: "steam-shock",
    name: "蒸汽震荡",
    description: "燃烧目标受到寒冰命中时爆出蒸汽冲击，造成范围伤害并追加短减速。",
    baseElement: "fire",
    triggerElement: "ice",
    damageMultiplier: 0.82,
    radius: 94,
    followupElementState: {
      element: "ice",
      timer: 0.75,
      reactionLockTimer: 0.14,
    },
  },
  {
    id: "conductive-shatter",
    name: "导电碎裂",
    description: "寒冰挂载受到雷击时导出碎裂电弧，对周围敌人形成连锁清场。",
    baseElement: "ice",
    triggerElement: "lightning",
    damageMultiplier: 0.58,
    radius: 118,
    chainCount: 3,
    chainDamageMultiplier: 0.42,
  },
  {
    id: "melt-pierce",
    name: "熔蚀穿透",
    description: "寒冰挂载受到火焰命中时熔解目标，短时间内提高其承伤并打开爆发窗口。",
    baseElement: "ice",
    triggerElement: "fire",
    damageMultiplier: 0.7,
    radius: 0,
    applyMelted: true,
    meltedDuration: 2.2,
  },
];

export const heroCoreUpgradePool: Record<HeroClass, UpgradeOption[]> = {
  warrior: [
    {
      id: "warrior-cinder-heart",
      kind: "hero-core",
      title: "炽心储焰",
      description: "怒焰上限 +20，点燃阈值 -8，更容易进入爆发窗口。",
      rarity: "rare",
    },
    {
      id: "warrior-berserk-drive",
      kind: "hero-core",
      title: "狂战推进",
      description: "怒焰爆发持续时间延长，并进一步提高爆发期间的斩击伤害。",
      rarity: "epic",
    },
    {
      id: "warrior-scorch-guard",
      kind: "hero-core",
      title: "灼痕护甲",
      description: "怒焰衰减变慢，近战命中时额外回复生命，适合贴身压场。",
      rarity: "rare",
    },
  ],
  ranger: [
    {
      id: "ranger-falcon-rhythm",
      kind: "hero-core",
      title: "猎鹰节律",
      description: "动量上限提高，移动蓄势带来的暴击收益更明显。",
      rarity: "rare",
    },
    {
      id: "ranger-weakpoint-burst",
      kind: "hero-core",
      title: "弱点引爆",
      description: "猎印更快引爆，并提高引爆半径与追加伤害。",
      rarity: "epic",
    },
    {
      id: "ranger-trail-sight",
      kind: "hero-core",
      title: "追迹视界",
      description: "猎印持续时间更长，保持走位时能更稳定锁定高价值目标。",
      rarity: "rare",
    },
  ],
  mage: [
    {
      id: "mage-prism-memory",
      kind: "hero-core",
      title: "棱镜记忆",
      description: "法印协鸣持续更久，并额外扩大协鸣期间的法术范围。",
      rarity: "rare",
    },
    {
      id: "mage-spellweave",
      kind: "hero-core",
      title: "织印施法",
      description: "主动施法会额外记录 1 枚同元素法印，更快形成法印矩阵。",
      rarity: "epic",
    },
    {
      id: "mage-arcane-surge",
      kind: "hero-core",
      title: "秘流奔涌",
      description: "法印协鸣的伤害强化提高，让法球和主动技都更具终结力。",
      rarity: "rare",
    },
  ],
};
